apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets:
              - "prometheus.default.svc.cluster.local:9090"
      - job_name: "kube-state-metrics"
        static_configs:
          - targets:
              - "kube-state-metrics.default.svc.cluster.local:8080"

      - job_name: "todo-backend"
        metrics_path: /metrics
        static_configs:
          - targets:
              - "nginx.default.svc.cluster.local:80"
            
      - job_name: "postgres"
        static_configs:
          - targets: [postgres-exporter:9187]


#      - job_name: "node-exporter"
#        static_configs:
#          - targets:
#              - "node-exporter-prometheus-node-exporter.default.svc.cluster.local:9100"
